### ISSUE TITLE
Document supported config overrides

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/superset-operator#117]
Most settings can be overridden today already even though they are not exposed as fields in the CRD.
This functionality however is hidden and not documented.

Please document all the possible files, CLI and Env (if applicable) that can be overridden.

You can take a look at the Druid PR: https://github.com/stackabletech/druid-operator/pull/154
But please feel free to improve if you find anything.

**Comment by fhennig** [comment]
There is nothing to document at the moment because no config file is written. We first need to implement that. For environment variables it looks like superset does not read anything from the environment.

My suggestion would be to close this issue for now and open a new one "Implement configuration for superset" and add the config overrides to that story.

Superset doesn't use the .properties format for the config, instead it uses a .py file that seems to just get loaded in (and it can contain arbitrary code too, maybe not ideal). We need to write a formatter for that as well to support the overrides so it's not just about documenting a feature.

Link to the docs: https://superset.apache.org/docs/installation/configuring-superset

**Comment by siegfriedweber** [comment]
Overrides documented in #173
